# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
before_install:
- gem install cocoapods -v 1.6.0.beta.2

script:
- xcodebuild -workspace SwiftChaining_mac.xcworkspace -scheme SwiftChaining_mac_tests -configuration Debug OBJROOT=build -sdk macosx clean test
- xcodebuild -workspace SwiftChaining_ios.xcworkspace -scheme SwiftChaining_ios_tests -configuration Debug OBJROOT=build -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=12.1' clean test
- pod lib lint
